### ISSUE TITLE
Review: CommitToEvent and EventList

### ISSUE THREAD

**Issue by aldenparoni** [Ube-Dev/Voluntree#102]
## Overview

The focus for this code review will be centered around the CommitToEvent and EventList components.    
Please pay attention to:
* JavaScript issues
* React components
* Meteor calls

## Review Branch

review-102

## Files to review

* CommitToEvent.jsx
* EventList.jsx

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [Meteor](../blob/main/checklists/meteor-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

Checklists can also be found in the /checklists folder in the Voluntree repo.

## Due date

Monday, February 26 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ryanseng03** [comment]
## CommitToEvent.jsx
- Could not find anything wrong

## EventList.jsx
- Also could not find anything wrong

**Comment by thomasarivera** [comment]
## CommitToEvent.jsx

DE-06: L29, L53, Add space for readability.

## EventList.jsx

TA-02: No test for search.

**Comment by Jchen20-1** [comment]
## CommitToEvent.jsx

JS-07: Missing JSdoc for component. L17

## EventList.jsx

JS-07: Missing JSdoc for component. L7
L16: idk if its intentional, but !!event.target.value?

**Comment by sierranmorales** [comment]
## CommitToEvent.jsx
L17, 53 Add space for better readability

## EventList.jsx
L119 Add space for better readability

**Comment by jianleliu** [comment]
### CommitToEvent
good

### EventList
good

**Comment by hokwaichan** [comment]
**CommitToEvent.jsx**
New line when needed

**EventList.jsx**
Looks good

**Comment by aldenparoni** [comment]
## CommitToEvent.jsx

L33: Will the "Connect" button have a different function than "Commit"? Right now it does the same thing as Commit.
AR-01: If clicking "Connect" does something different, I think it would make more sense to rename this "CommitConnect.jsx". 

## EventList.jsx

ES-01: L19: ESLint gives warning - "Variable initializer is redundant"

**Comment by thomasarivera** [comment]
## Outcome of meeting

New issues:

- Fixed code readability and added comments in CommitToEvent.jsx
- Added comments and fixed code error in EventList.jsx
Resolved in this branch.
