### ISSUE TITLE
Notifications Collection

### ISSUE THREAD

**Issue by Jchen20-1** [Ube-Dev/Voluntree#121]
Please do work for this task in a branch called issue-XXX.

**Comment by jianleliu** [comment]
* created new Notification collection
* sendNotification meteor method take in {
  receivers: [userID],
  senderGroup: one of ['ORGANIZATION', 'USER'],
  sender: 'organizationID',
  title: 'sample notification',
  content: 'sample content', // this can be html string too.
}
  - createdDate is automatically set when new notification is inserted into the db.
* two subscriptions:
  - subscribeUserNotification(userID):
    - input: userID of UserProfile.
    - returns: a subscription containing this userID as a receiver and sender, else null.

  - subscribeOrganizationNotification(organizationID)
    - input: organizationID of OrganizationProfile.
    - returns: a subscription containing this organizationID as a sender.
