### ISSUE TITLE
Review: GoBackButton and UpcomingEventCard

### ISSUE THREAD

**Issue by aldenparoni** [Ube-Dev/Voluntree#128]
## Overview

The focus for this code review will be centered around the GoBackButton and UpcomingEventCard components.  

Please pay attention to:
* Javascript issues
* React components
* Meteor calls

## Review Branch

review-128

## Files to review

* GoBackButton.jsx
* UpcomingEventCard.jsx

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [Meteor](../blob/main/checklists/meteor-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

Checklists can also be found in the /checklists folder in the Voluntree repo.

## Due date

Monday, March 11 @ 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by aldenparoni** [comment]
## GoBackButton.jsx

L8: Inline styling; I think we can give it a className from a separate .css file instead

## UpcomingEventCard.jsx

L9: ES-01 - CommitToEvent is not being used
L54-55: Inline styling; I think they can be styled from style.css or at least a separate .css file, that way the lines don't have to be so long to the point ESLint says something about it
L43, L55: Is there a difference between using <a> and using <Link>? I've wrapped a Link component around a Button component for one of my issues (see EditUserProfile.jsx, L79), but then somewhere else I saw that you can just add `href` to the Button component (see UserProfile.jsx, L76). Is there a way we can be a bit more consistent on which one we use? Just a thought.

**Comment by Jchen20-1** [comment]
## GoBackButton.jsx

Missing JSDoc
L8: For styling the button, could probably create a separate css file or give a class just because all of our buttons seems to use that styling

## UpcomingEventCard.jsx

L9: CommitToEvent is not used, please remove
Same comment about using styling for the buttons as GoBackButton

**Comment by thomasarivera** [comment]
## GoBackButton.jsx

TA-01: Each Page has an isDisplayed() acceptance test.
TA-02: Each form has an acceptance test.

Use button css from style.css for uniformity.

## UpcomingEventCard.jsx

TA-01: Each Page has an isDisplayed() acceptance test.
TA-02: Each form has an acceptance test.
ES-01: L9, CommitToEvent is not used, please delete.
L50, Add a margin to the top and bottom for spacing.

Use button css from style.css for uniformity.

**Comment by willjsimmons** [comment]
In addition to the messages above.
# Go Back Button
No additional comments to be added:
# UpcomingEventCard
* DE-07: Ensure code is DRY. My Ide flags line 13 as repeat. 
* It could be that it is not an issue.
* DE-01 Perhaps it can be refactored.
*DE-03 unused import as mentioned above.

**Comment by jianleliu** [comment]
### GoBackButton
move in line css to a css file

### UpcomingEventCard
CommitToEvent not used
move in line css to a css file

**Comment by thomasarivera** [comment]
## Outcome of Review Meeting

New issues:

- Create isDisplayed() and acceptance test for both pages. This will be resolved in issue 129.
- Fix button CSS in both files.
- UpcomingEventCard.jsx: Remove Es-Lint error and implement UI improvements.

**Comment by hokwaichan** [comment]
**Go Back Button**
Can move CSS to CSS file


**UpcomingEventCard**
L9 unused import 
Can move CSS to CSS file
