### ISSUE TITLE
Review: CreateOrganization and UserCalendar

### ISSUE THREAD

**Issue by thomasarivera** [Ube-Dev/Voluntree#134]
## Overview

The focus for this code review will be centered around the CreateOrganization page and UserCalendar component.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-134

## Files to review

* CreateOrganization.jsx
* UserCalendar.jsx

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Monday, March 25 @ 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by hokwaichan** [comment]
**CreateOrganization**
Remove L13 comment
L95 fix eslint
L37, L92 change contactEmail to email

**UserCalendar**
Move style to separate css

**Comment by sierranmorales** [comment]
## CreateOrganization.jsx
L13 remove unnecessary comment
L95 resolve ESLint error

## UserCalendar.jsx
L29, 76, 77, 86, 87 move style to CSS file

**Comment by ryanseng03** [comment]
## CreateOrganization.jsx
L13: Remove placeholder comment.

## UserCalendar.jsx
- Could use more detailed comments.
- HTML portion of the code at the end.. the styling can be in a separate CSS file.
- A week view would be nice as well if it could be implemented.

**Comment by aldenparoni** [comment]
## CreateOrganization.jsx

- L13: DE-03, delete comment
- TA-02: Component IDs for lines L78, L81, L84, L87, L99, L119, L122, L125, L128, L131 are not resolved, will affect acceptance testing for this page
- L122: Zip Code should be placed in between State and Country to match address format convention 

## UserCalendar.jsx

- L29, L76, L77, L86, L87: in-line styling -- we should move and/or modify the styling to a separate CSS file, whether in style.css or in another CSS file
- TA-01: I don't think it would hurt for this to have an isDisplayed() acceptance test

**Comment by Jchen20-1** [comment]
## CreateOrganization.jsx

L78-L87, L99, L119-L131: Component Ids don't exist in the ComponentIDs.js file. 

## UserCalendar.jsx

in line styling, can maybe move to css file

**Comment by thomasarivera** [comment]
## CreateOrganization.jsx

DE-03: L13, Eliminate dead code.
DE-05: L108, L115, Ensure comments are appropriate. Add comments for clarity about "hasAddress" variable.

## UserCalendar.jsx

DE-06: L61, Ensure code is readable. Intergrate code with other return code block for simplicity.
Optimize for smaller screens.
Move styles to a css file.

**Comment by jianleliu** [comment]
### CreateOrganization.jsx
L13: remove unused code.
L95: fix eslint.

### UserCalendar.jsx
move styles to a css file.

**Comment by thomasarivera** [comment]
## Outcome of Review Meeting

New issues:

- Fix issues in CreateOrganization.jsx. This will be resolved in review--134.
- Move style code to a new CSS file and fix other issues. This will be resolved in issue-xxx.
