### ISSUE TITLE
Review: SubscriptionPage and OrganizationDropdown

### ISSUE THREAD

**Issue by thomasarivera** [Ube-Dev/Voluntree#136]
## Overview

The focus for this code review will be centered around the Subscription page and OrganizationDropd.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-136

## Files to review

* SubscriptionPage.jsx
* OrganizationDropdown.jsx

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Monday, April 1 @ 11PM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ryanseng03** [comment]
## SubscriptionPage.jsx
- L22 Typo 'imporve' to 'improve'.
- Everything else looks good!

## OrganizationDropdown.jsx
- Looks good.

**Comment by Jchen20-1** [comment]
## SubscriptionPage.jsx

L22: type in word improve
L28: in line styling even though theres a dedicated css file

## OrganizationDropdown.jsx

looks good overall, might have to change functionality of the join buttons later on

**Comment by sierranmorales** [comment]
## SubscriptionPage.jsx
L9 Capitalize "C" in "create"
L22 Typo: change "imporve" to "improve"
L28 Move style to CSS file instead of inline

## OrganizationDropdown.jsx
Consider adding more comments for better readability

**Comment by hokwaichan** [comment]
**SubscriptionPage.jsx**
L22 typo
Looks good

**OrganizationDropdown.jsx**
Looks good

**Comment by willjsimmons** [comment]
# OrganizationDropdown

```
Although these are not problematic,
and the code is relatively readable, all I can think to add is.

* DE-05: Ensure comments are appropriate
* DE-06: Ensure code is readable

```
# SubscriptionPage.jsx

```
	I do not see any issues with this file other than the ones already mentioned..
```

**Comment by jianleliu** [comment]
### SubscriptionPage.jsx
* L22: imporve > improve
* L28: style={{ color: 'gold' }} to .css file

### OrganizationDropdown.jsx
* Looks good.

**Comment by thomasarivera** [comment]
## Outcome of Review Meeting
New issues:
- Fix typo and styling issue in SubscriptionPage.jsx and comment implementation in OrganizationDropdown.jsx. This will be resolved in review-136.
- Acceptance tests will be resolved in issue-xxx.
