### ISSUE TITLE
SubscriptionPage and OrganizationDropdown: Acceptance Tests

### ISSUE THREAD

**Issue by thomasarivera** [Ube-Dev/Voluntree#137]
Please do work for this task in a branch called issue-137.

Create acceptance tests for the following page and component:

- [x] SubscriptionPage.jsx
- [x] OrganizationDropdown.jsx

**Comment by aldenparoni** [comment]
I created acceptance tests for OrganizationDropdown as part of working on issue-153.

**Comment by thomasarivera** [comment]
I created acceptance tests for SubscriptionPage as part of working on issue-173.
