### ISSUE TITLE
Bug fixes after new backend updates

### ISSUE THREAD

**Issue by Jchen20-1** [Ube-Dev/Voluntree#138]
Please do work for this task in a branch called issue-138.

Fix:

- [x] committing to events returns error (most likely just need to update the meteor methods being used to update users and events collection)
- [x] User Profile page shows blank for the user's image, most likely a typo somewhere since the homepage has the image working
- [x] dashboard dropdown and page doesn't show the list of organizations even after confirming that the organization was created and added to the Organization collection. 
- [x] adding events requires a new category field, where it has the mainCategory and subCategory, need to create new fields in the form when creating events.

**Comment by jianleliu** [comment]
activityCategories
- mainCategory
- subCategory

will not be optional and default to "Other".
