### ISSUE TITLE
Add Volunteer Hours Method

### ISSUE THREAD

**Issue by thomasarivera** [Ube-Dev/Voluntree#144]
Please do work for this task in a branch called issue-144.

Implement a method to add volunteer hours for a user. After scanning a user's QR code, the method should be add the volunteer hours to the user's profile.

**Comment by jianleliu** [comment]
new meteor method userAddHours
 * input: docID - _id of userProfile, string
          hour - hours to be added, Number(not {}, just int)
 * return: # of userProfiles affected.
