### ISSUE TITLE
Review: EditEvent and OrgEventCard

### ISSUE THREAD

**Issue by aldenparoni** [Ube-Dev/Voluntree#152]
## Overview

The focus for this code review will be centered around the EditEvent page and OrgEventCard component. 

Please pay attention to:
* Javascript issues
* React components
* Meteor calls
* In-line styling

## Review Branch

review-152

## Files to review

* EditEvent.jsx
* OrgEventCard.jsx

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Meteor](../../checklists/meteor-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Monday, April 8 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by hokwaichan** [comment]
**EditEvent.jsx**
Adding more comments for clarity 
Some lines are quite long can consider breaking them into multiple lines to improve readability

**OrgEventCard.jsx**
Can add comments for clarity 
Looks good

**Comment by ryanseng03** [comment]
## EditEvent.jsx
- Looks good

## OrgEventCard.jsx
- Looks good
- Maybe some comments would be nice.

**Comment by sierranmorales** [comment]
## EditEvent.jsx
Add more comments for better readability

## OrgEventCard.jsx
L7, L9 Consider moving style to CSS file
Add comments for better readability

**Comment by Jchen20-1** [comment]
## EditEvent.jsx

looks good

## OrgEventCard.jsx

L17 L20 the buttons have "commit-btn" as class names, can consider making an universal class for all our button stylings

**Comment by aldenparoni** [comment]
## EditEvent.jsx

TA-01: needs isDisplayed() acceptance test, page id is a good start
TA-02: form needs acceptance test, component ids are a good start

## OrgEventCard.jsx

L6, L37, L55: even though file name is OrgEventCard, the export is still named "EventCard", please change to "OrgEventCard" to match file name
L7, L9: in-line styling, move to separate CSS file

**Comment by jianleliu** [comment]
### EditEvent.jsx
Looks good.

### OrgEventCard.jsx
L7, L9: Move css to a .css file.

**Comment by willjsimmons** [comment]
# OrgEventCard
-----

AR-01/JS-01/RE-08 : org event card exports EventCard not OrgEventCard

# EditEvent
------

DE-07 : For the most part this file seems fine.
Perhaps it is a bit repetative.

**Comment by thomasarivera** [comment]
## EditEvent.jsx

TA-01:Each Page has an isDisplayed() acceptance test
TA-02: Each form has an acceptance test.

## OrgEventCard.jsx

TA-01:Each Page has an isDisplayed() acceptance test
TA-02: Each form has an acceptance test.

**Comment by aldenparoni** [comment]
## Outcome of meeting:
### Changes made in review branch and pushed to main:
#### OrgEventCard.jsx
- Renamed export in OrgEventCard.jsx to match file name
- Changed className for Edit and View buttons to primary variant styling, since we have styling for btn-primary
- Moved in-line styling to EventCard.css 
  - In-line styling in EventCard.jsx was also moved to EventCard.css
  - EventCard.css now provides styling for both OrgEventCard and EventCard

### New issues:
- Acceptance tests for OrgEventCard and EditEvent (will be resolved in issue-151)
