### ISSUE TITLE
Add Org Hours Method

### ISSUE THREAD

**Issue by thomasarivera** [Ube-Dev/Voluntree#157]
Please do work for this task in a branch called issue-157.

Implement a method to add hours for an Org. After scanning a user's QR code, the method should add the hours to the Org's profile.

**Comment by jianleliu** [comment]
* new meteor method: organizationAddHours
  - input: docID, hours(just int, not {})
  - return number of entity modified(should be one)

  - This increments totalHours and monthlyHours in the collection.
    - There are 2 ways to implemnet monthlyHours
      1. reset it to 0 at the start of the month HST
      2. save the past monthlyHours in either an array or object.
    - Currently totalHours and monthlyHours is the same.
