### ISSUE TITLE
Review: UserDashboard.jsx and TosModal.jsx

### ISSUE THREAD

**Issue by Jchen20-1** [Ube-Dev/Voluntree#174]
Please do work for this task in a branch called review-174.

## Overview

The focus for this code review will be centered around the TosModal and UserDashboard components/pages.  

Please pay attention to:
* Javascript issues
* React components
* Meteor calls

## Review Branch

review-174

## Files to review

* UserDashboard.jsx
* TosModal.jsx

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [Meteor](../blob/main/checklists/meteor-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

Checklists can also be found in the /checklists folder in the Voluntree repo.

## Due date

Monday, April 22nd @ 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ryanseng03** [comment]
## UserDashboard.jsx
- L44, Declare ID in ComponentIDs as well
- Looks good

## TosModal.jsx
- Could add some comments in the beginning
- Also looks very nice.

**Comment by Jchen20-1** [comment]
## UserDashboard.jsx

L44: USER_DASHBOARD_VIEW_QR_CODE component ID doesn't exist

## TosModal.jsx

L15: can maybe use <Container> instead of <div>

**Comment by jianleliu** [comment]
### UserDashboard.jsx
L41: use _id instead of id

### TosModal.jsx
Looks good

**Comment by sierranmorales** [comment]
## UserDashboard.jsx
L44 unresolved variable

## TosModal.jsx
Looks good

**Comment by aldenparoni** [comment]
## UserDashboard.jsx
- L44: need to check ComponentIDs.jsx to get the correct component id for TestCafe

## TosModal.jsx
- looks fine

**Comment by thomasarivera** [comment]
## UserDashboard.jsx

DE-05: Ensure comments are appropriate. Add comments for clarity and its function.

## TosModal.jsx

TA-01:Each Page has an isDisplayed() acceptance test
TA-02: Each form has an acceptance test.

**Comment by willjsimmons** [comment]
# UserDashboard.jsx
 Looks Good.

#TosModal.jsx
 Looks Good.

No Other than the issues mentioned above.

**Comment by thomasarivera** [comment]
## Outcome of meeting:
### Changes made in review branch and pushed to main:
#### UserDashboard.jsx

Implement comments for code readability and fix errors.

#### TosModal.jsx

Implement react components.

#### New issues:

    Acceptance tests for UserDashboard (will be resolved in issue-175)

**Comment by hokwaichan** [comment]
**UserDashboard.jsx**
- Can add comments for readability
- Missing component_ids USER_DASHBOARD_VIEW_QR_CODE

**TosModal.jsx**
- Looks good
