### ISSUE TITLE
Review: AdminOrganizationModeration.jsx and AdminHome.jsx

### ISSUE THREAD

**Issue by thomasarivera** [Ube-Dev/Voluntree#183]
## Overview

The focus for this code review will be centered around the AdminOrganizationModeration.jsx page and AdminHome.jsx component.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-183

## Files to review

* AdminOrganizationModeration.jsx 
* AdminHome.jsx

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Monday, April 29th @ 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by thomasarivera** [comment]
## AdminOrganizationModeration.jsx

TA-02: Each form has an acceptance test.
L109: eslint error - add alt to Image 

## AdminHome.jsx

TA-02: L31 - Each form has an acceptance test.

**Comment by Jchen20-1** [comment]
## AdminOrganizationModeration.jsx

L89: component ID doesn't exist (ORGANIZATION_SEARCHBAR)

## AdminHome.jsx

Looks good

**Comment by aldenparoni** [comment]
## AdminOrganizationModeration.jsx

- L80: component id does not exist

## AdminHome.jsx

- looks good

**Comment by jianleliu** [comment]
### AdminOrganizationModeration.jsx
looks good

### AdminHome.jsx
looks good

**Comment by hokwaichan** [comment]
**AdminOrganizationModeration**
L80 component id does not exit
Can add comments

**AdminHome.jsx**
Looks good

**Comment by willjsimmons** [comment]
#AdminOrganizationModeration
Other than the aforementioned! it looks good

#AdminHome.jsx
Looks good

**Comment by aldenparoni** [comment]
## Outcome of review meeting

Work done in this branch:
- lint fixes
- additional component ids
- short comment after module imports describing each component

New issue:
- testcafe tests for AdminOrganizationModeration.jsx and the rest of the existing admin mod pages (will be done in a separate issue)
