### ISSUE TITLE
Review: NavBar and OrganizationProfileCollection

### ISSUE THREAD

**Issue by aldenparoni** [Ube-Dev/Voluntree#43]
## Overview

The focus for this code review will be centered around the navbar and our Organizations collection.    
Please pay attention to:
* JavaScript issues
* React components

## Review Branch

review-43

## Files to review

* [NavBar.jsx](https://github.com/Ube-Dev/Voluntree/blob/8dbc678d6d4adf21017210850dc2d253241d7a31/app/imports/ui/components/NavBar.jsx)
* [OrganizationProfileCollection.js](https://github.com/Ube-Dev/Voluntree/blob/8dbc678d6d4adf21017210850dc2d253241d7a31/app/imports/api/user/OrganizationProfileCollection.js)

## Checklists

* [Architecture](Voluntree/checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Monday, January 29 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by thomasarivera** [comment]
## NavBar.jsx
___
DE-06: Separate Role-specific sections with empty lines or comments.

## OrganizaitonProfileCollection.js
___
DE-03: L29, L40, L41 Unused commented out code.

**Comment by aldenparoni** [comment]
## Navbar.jsx

L35, 38, 39: This may be nitpicky, but the COMPONENT_IDS of these links are not consistent with the other ids. Notice how L34 has `id={COMPONENT_IDS.NAVBAR_ABOUT_PAGE}`? The component ID for FAQ doesn't have `_PAGE` at the end. Maybe we could add that and make the changes wherever else needed for the testing? 
L41-42, 45-46: The brackets are not next to the parentheses like in the other uses of the ternary operator in this file.
L56: Still needs a component id and a NavLink to the Profile page (although I'm working on that right now)

## OrganizationProfileCollection.js

L29, 36, 40, 41, 93: DESIGN-03: If these commented lines of code are not needed, please delete.
L35, 37: ESLINT-01: On IntelliJ, the warning says "Local variable 'profileID' is redundant". Could we simplify these lines into one return statement, and maybe add a comment clarifying what the return statement does?

**Comment by sierranmorales** [comment]
**NavBar.jsx:**
	
Perhaps add comments for better readability 

I noticed that when the window is resized smaller, navbar items disappear.



**OrganizationProfileCollection.js:**

There seem to be some testing comments that may be removed.

**Comment by Jchen20-1** [comment]
## NavBar.jsx:

L35: Naming convention on the id is not consistent with the rest of the page. 
Overall: comments needed on sections to explain what each check on currentUser is checking for, and what should be/is displayed in the navbar. 

## OrganizationProfileCollection.jsx:

L29, L36, L41, L93 remove unnecessary comments that were use for testing

**Comment by ryanseng32** [comment]
### NavBar.jsx:

Add comments to explain each Nav Link

### OrganizationProfileCollection.js

L29, L36, L40, L41, L93: Most likely placeholders for later, but if possible, remove when no longer needed.

**Comment by jianleliu** [comment]
**OrganizationProfileCollection.js**
	
*maybe write a separate file with the db fields and their relationship and what they means. 
*remove unused code
*use switch statement instead of multiple if statements

**NavBar.jsx**
*more comments

**Comment by hokwaichan** [comment]
**NavBar.jsx:**
Line 35 COMPONENT_IDS.NAVBAR_FAQ should be COMPONENT_IDS.NAVBAR_FAQ_PAGE
Line 37 and Line 42 bracket are placing differently  

**OrganizationProfileCollection.js:**
Design-05: Some unnecessary comments

**Comment by aldenparoni** [comment]
## Outcome of meeting

New issues (will be resolved in the review-43 branch):
- NavBar.jsx: Add comments for better understanding; Add _PAGE to end of component IDs for consistency
- OrganizationProfileCollection.js: Delete unnecessary commented lines
