### ISSUE TITLE
Review: EventCard and SignIn

### ISSUE THREAD

**Issue by aldenparoni** [Ube-Dev/Voluntree#53]
## Overview

The focus for this code review will be centered around the EventCard component and SignIn page.    
Please pay attention to:
* Javascript issues
* React components
* Meteor issues

## Review Branch

review-53

## Files to review

* EventCard.jsx
* SignIn.jsx

## Checklists

* [Architecture](../checklists/architecture-checklist.md)
* [Design](../checklists/design-checklist.md)
* [JS](../checklists/js-checklist.md)
* [React](../checklists/react-checklist.md)
* [Testing](../checklists/testing-checklist.md)

## Due date

Monday, February 5, 2024 11pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by aldenparoni** [comment]
## EventCard.jsx

L30: Not sure why ESLint is saying this is a typo, "accessibilities" is a real word.
L22-L36: Not all the fields here are displayed in the visual component. Are we going to incorporate the rest in future milestones, or is this something that might be changed according to the new database design?
L13: Is it possible to do something like,

This expedition is a chance for your family to step out of their comfort zone and discover a world beyond their own. As you immerse in a new culture, your children will learn firsthand... <u>View more</u> 

and the "view more" link goes to an expanded page of the event? What I mean is, once a description reaches a certain amount of characters, cut off the rest with "..." and include the link to view the rest of the event. Just an idea.

L11-L14: Putting my suggestion aside, would the buttons for Commit and/or Connect be under the description once we have them?

## SignUp.jsx

L70: I think it would be nice if the Submit button was styled as well. I think I was able to do that with a previous project. The shade of blue doesn't feel consistent with the color scheme we're going for.

### Questions about SignUp.jsx:
- Should we rename this to "UserSignUp.jsx" since this for users to sign up? We'll have an organization sign-up page that might look similar to this page but it creates org accounts.
- As far as the styling for this (and also SignIn.jsx) goes, are the white outlines okay? Should we make the cards more boxy?

**Comment by thomasarivera** [comment]
## EventCard.jsx

DE-05: L21, Comment may not be required

## SignIn.jsx

DE-05: L26, L35, L38, L39, Unused code or unnecessary comments.

**Comment by willjsimmons** [comment]
Event Card 
 Event card seems to meat all of the requirements in all applicable checklists.
 The only considerations to be made are aesthetic considerations. 
 Thus far the aesthetic fits with the rest of our system.
 Perhaps JS-7 is to be considered adding javadoc comments. to Event Card.
 also this page fits our camel case convention starting with an upercase letter.
 SignIn page:
DE-04 / DE-05 : sign in page has several dead comments.

**Comment by sierranmorales** [comment]
##EventCard.jsx
Could add more descriptive comments

##SignIn.jsx
L26, 35, 39 remove unnecessary comments

**Comment by ryanseng32** [comment]
## EventCard.jsx
- Not all propTypes are being used in the card component, could be implemented in the future as a standalone page when expanding.
- Because EventCard is working well, in AllEventsPage, the long commented out code and be removed.

## SignIn.jsx
- Submit button could be styled as a lighter color.
- The placeholder and the title of the TextFields seems a little redundant as they are both repeated.
- L63: The 'click here to register' field seems too big and could be shrunk to blend in with the background, similar to other websites with this feature.
-

**Comment by Jchen20-1** [comment]
EventCard.jsx

DE-6 could use some comments to explain the code a little
RE-10 L38 avoid Card in the name of the component as it renders multiple cards depending on the data given.


SignIn.jsx

DE-5 L26, 35, 39 some lingering comments of console.logs

**Comment by hokwaichan** [comment]
**EventCard.jsx**
Design-05: L21 unnecessary comment
L30 accessibilities showed as a typo, could change it to accessibility

**SignIn.jsx**
Design-05: There are some unnecessary comments 26, 35, etc

**Comment by jianleliu** [comment]
SignIn page:
*add a forget password and forget email link

Event Card:
*seems good to me.
