### ISSUE TITLE
Review: UserProfileCollection.js and UserCollection.js

### ISSUE THREAD

**Issue by Jchen20-1** [Ube-Dev/Voluntree#84]
## Overview

The focus for this code review will be centered around the Landing page and UserDashboard component.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-84

## Files to review

* UserProfileCollection.js
* UserCollection.jsx

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, February 19, 11:30 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by Jchen20-1** [comment]
## UserCollection.js

L53 DE-5 useless comment


## UserProfileCollection.js

L127 still says EventCollection
L157 seems like dead function, could maybe remove/code our own if we need to use it

**Comment by aldenparoni** [comment]
## UserCollection.js

L53, L73-74: DE-03 dead comments

## UserProfileCollection.js

JS-07: It would be nice if there was JSDoc comments listing what each field in the collection should hold. For this collection it would be tedious, but very much needed. I suggest right before the class declaration, somewhere around L14.

L75-L82: Consolidate this code to just a single return statement. Maybe add a comment above it.

L177: I think "User" needs to be capitalized here? `ROLE.USER`?

L200: Comment typo, should be "Provides"

**Comment by sierranmorales** [comment]
##UserCollection.js:
L53, 73, 74, 84 Remove unnecessary comments

##UserProfileCollection.js:
L127 Comment says EventCollection
L200 Typo in comment: “Profides” instead of “Provides”

**Comment by jianleliu** [comment]
### UserProfileCollection:
Add validation to check if the entity exists in other collections when defining/updating.

implement load/dump

write more sophisticated subscribe functions

add more comments

### UserCollection
remove dead comments

**Comment by thomasarivera** [comment]
## UserCollection.js
DE-05, L53, L73, L74, L84: Unused code and comments

##UserProfilecollection.js
DE-05, L164: Unused code

**Comment by hokwaichan** [comment]
**UserCollection**
Some unnecessary comments

**UserProfilecollection**
L200 typo "Profides"
Some unnecessary comments

**Comment by ryanseng32** [comment]
## UserCollection.js
L53, L73, L74, L84: Remove the unused comments.

## UserProfileCollection.js
L127 Comment says EventCollection.
L200 “Profides” typo

**Comment by aldenparoni** [comment]
## Outcome of meeting

New issues:
- Fix comment typos and add comments to both UserCollection.js and UserProfileCollection.js (resolved in this branch)
