### ISSUE TITLE
Optimize UserCalendar

### ISSUE THREAD

**Issue by hokwaichan** [Ube-Dev/Voluntree#97]
Please do work for this task in a branch called issue-97.

Make the following changes:

- [x] Optimize calendar for smaller screens.
- [x] Move style code to a new CSS file.
- [x] implement more comments for clarity
- [x] DE-06: L61, Ensure code is readable. Intergrate code with other return code block for simplicity.

**Comment by thomasarivera** [comment]
Completed as apart of issue-182
